### ISSUE TITLE
[1- Introdução]

### ISSUE THREAD

**Issue by Mury12** [Mury12/mqtt#2]
Introdução do minicurso pode ser tomado como fonte [este artigo](https://www.ibm.com/developerworks/br/library/iot-mqtt-why-good-for-iot/index.html) da IBM.

- Tópicos a serem abordados na introdução:
- [x] O que é MQTT, um pouco da história dos protocolos e sua evolução;
- [x] Funcionamento do protocolo;
- [x] Aplicabilidade.

**Comment by Mury12** [comment]
problema blablabla

**Comment by Mury12** [comment]
@mury12

**Comment by AndreArantes** [comment]
https://docs.google.com/presentation/d/14yj5nj50lQoyeQsPWH43A4skR6qvP9x2CMZP_tWas0k/edit?usp=sharing **link dos slides**
